In [1]:
## PANDAS & NUMPY

In [2]:
import numpy as np

In [3]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [4]:
## Multidimentional Array

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.random.seed(123)
raw_scores = np.random.normal(loc = 60, scale = 10, size = 100)

In [9]:
## Working with data

In [10]:
raw_scores

array([49.14369397, 69.97345447, 62.82978498, 44.93705286, 54.21399748,
       76.51436537, 35.73320757, 55.71087371, 72.65936259, 51.33259598,
       53.21113848, 59.05291031, 74.91389626, 53.61098003, 55.5601804 ,
       55.65648724, 82.05930083, 81.86786089, 70.04053898, 63.86186399,
       67.37368576, 74.90732028, 50.64166132, 71.75829045, 47.46119332,
       53.62248498, 69.07105196, 45.713193  , 58.5993128 , 51.38245104,
       57.44380629, 32.01410895, 42.28466895, 53.00122765, 69.27462432,
       58.26364317, 60.02845916, 66.88222711, 51.20463657, 62.83627324,
       51.94633482, 42.72330506, 56.09100206, 65.73805862, 63.38589051,
       59.88169506, 83.92365266, 64.1291216 , 69.78736006, 82.38143338,
       47.05914677, 49.6121179 , 77.43712225, 52.01937265, 60.2968323 ,
       70.69315969, 68.90706391, 77.54886182, 74.95644137, 70.6939267 ,
       52.27291286, 67.94862668, 63.14271995, 46.7373454 , 74.17299046,
       68.07236535, 60.45490081, 57.66907939, 48.01698855, 61.99

In [11]:
raw_scores.ndim # dimention

1

In [12]:
raw_scores.shape  #### Number of element

(100,)

In [13]:
raw_scores.dtype

dtype('float64')

In [14]:
raw_scores.size

100

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a.shape

(2, 3)

In [17]:
a.ndim

2

In [18]:
a.size

6

In [19]:
# Reshape with Numpy

In [20]:
x = np.array([10, 20, 30, 40, 50, 60])
x.shape

(6,)

In [21]:
y = x.reshape(3,2) ## Reshaping the x array
print(y)

[[10 20]
 [30 40]
 [50 60]]


In [22]:
y.shape

(3, 2)

In [23]:
## Operations 

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
c = a * 2

In [26]:
print(c)

[[ 2  4  6]
 [ 8 10 12]]


In [27]:
## Quick analysis with numpy
# mean
# average
# min & max
# standard deviation 


In [28]:
scores = np.array([50, 60, 70, 80, 90, 55, 65, 75, 85, 90, 95, 100])

In [29]:
scores.mean()

np.float64(76.25)

In [30]:
scores.min()

np.int64(50)

In [31]:
scores.max()

np.int64(100)

In [32]:
from scipy import stats

In [33]:
mode_value = stats.mode(scores, keepdims=True)

In [34]:
mode_value

ModeResult(mode=array([90]), count=array([2]))

In [35]:
## Boolean indexing & Filtering

In [36]:
scores

array([ 50,  60,  70,  80,  90,  55,  65,  75,  85,  90,  95, 100])

In [37]:
scores >= 70

array([False, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True])

In [38]:
scores[scores >= 70]

array([ 70,  80,  90,  75,  85,  90,  95, 100])

In [39]:
scores[scores == 50]

array([50])

In [40]:
gender = np.array(["female", "Male", "Male", "female"])

In [41]:
gender[gender == "male"]

array([], dtype='<U6')

In [42]:
x

array([10, 20, 30, 40, 50, 60])

In [43]:
np.log(x)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456])

In [44]:
## Data Transformaation 

In [45]:
sales = np.array([10000, 12000, 14000, 16000, 280000, 20000])

In [46]:
sales_in_naira = sales / 1000

In [47]:
sales_in_naira

array([ 10.,  12.,  14.,  16., 280.,  20.])

In [48]:
# .clip fuction (used to cap extreeme values)

In [49]:
cliped_sales = np.clip(sales, a_min=0, a_max=100000)

cliped_sales

array([ 10000,  12000,  14000,  16000, 100000,  20000])

In [50]:
# Applying Logarithmic Transformation
sales_log = np.log(cliped_sales + 1)          # + 1 is added should incase there is "0" in the data
sales_log


array([ 9.21044037,  9.39274526,  9.54688403,  9.6804065 , 11.51293546,
        9.90353755])

In [51]:
import numpy as np

In [52]:
np.log(0)

C:\Users\PAUL\AppData\Local\Temp\ipykernel_14448\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


np.float64(-inf)

In [53]:
ages = np.array([20, 18, 24, 25, 23, 22])
ages

array([20, 18, 24, 25, 23, 22])

In [54]:
ages[0]  # acess first element. Python starts indexing from 0

np.int64(20)

In [55]:
ages[-1]  # for last element

np.int64(22)

In [56]:
scores = np.random.randint(5, 10, 20)

scores

array([6, 8, 6, 5, 6, 7, 7, 7, 6, 8, 7, 8, 6, 6, 8, 8, 7, 9, 5, 8],
      dtype=int32)

In [57]:
scores[2]

np.int32(6)

In [58]:
np.where(scores ==7) ## where index 7 is

(array([ 5,  6,  7, 10, 16]),)

In [59]:
## slicing and indexing

In [60]:
ages[1:4] ##indexing 0-3

array([18, 24, 25])

In [61]:
ages[:3] ## first 3 elements

array([20, 18, 24])

In [62]:
ages[3:] ## Indexing 3 to the end

array([25, 23, 22])

In [63]:
ages

array([20, 18, 24, 25, 23, 22])

In [64]:
ages[::2]   # every 2nd element

array([20, 24, 23])

In [65]:
ages[2] = 19 ## changing element at a particular position

In [66]:
ages

array([20, 18, 19, 25, 23, 22])

In [67]:
ages [2:4] = [21,20] # Replacing index 2: 4

In [68]:
ages

array([20, 18, 21, 20, 23, 22])

In [69]:
scores

array([6, 8, 6, 5, 6, 7, 7, 7, 6, 8, 7, 8, 6, 6, 8, 8, 7, 9, 5, 8],
      dtype=int32)

In [70]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [3, 6, 9]])

print(a)

[[1 2 3]
 [4 5 6]
 [3 6 9]]


In [71]:
a[:1:3]

array([[1, 2, 3]])

In [72]:
a[2:2]

array([], shape=(0, 3), dtype=int64)

In [73]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 9]])

In [74]:
a.sum(axis=1)   # Sum of each rows

array([ 6, 15, 18])

In [75]:
a.sum(axis=0)   # Sum of each columns

array([ 8, 13, 18])

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 9]])

In [77]:
a.T    # Transpose

array([[1, 4, 3],
       [2, 5, 6],
       [3, 6, 9]])

In [78]:
## ASS
## array([[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]]) 
# Get the sum,
#standard deviation
# sum of all columns in mat

In [79]:
import numpy as np
import pandas as pd

In [80]:
new_ages = np.array([[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
new_ages

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [81]:
new_ages.sum

<function ndarray.sum>

In [82]:
##Pandas


In [83]:
## Series = The column
## DAtaframe = The complete dataset

In [84]:
new_ages

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
x = 5 

if x > 10:
    print("A") 
elif x > 3: 
    print("B")
else: print("C")

B


In [86]:
registration_dict = {
    "gender": ["male", "female", "male", "male", "male", "female", "female"],
    "country": ["Niger", "Uganda", "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria"],
    "ages": [15, 19, 20, 25, 22, 30, 32]
}

In [87]:
## registration_dict

In [88]:
## A Dataframe
##  To arrage them in a particular order; do this;
# registration_dict_df = pd.DataFrame(registration_dict, columns = "gender", "country", "ages"])

registration_dict_df = pd.DataFrame(registration_dict)

registration_dict_df

gender  country  ages
0    male    Niger    15
1  female   Uganda    19
2    male  Nigeria    20
3    male  Nigeria    25
4    male  Nigeria    22
5  female  Nigeria    30
6  female  Nigeria    32

In [89]:
# creating manually 

import pandas as pd

data = [
    [39,36,55,"97/74",87,"Neg","35.00%","Neg","Nil","38/52","Ceph","Loa","HD","AA","O+","Neg","Neg",93,"Business"],
    [24,36,60,"95/59",73,"Neg","32.00%","Neg","Nil","36/52","Ceph","Loa","HD","", "A+","Neg","Neg",71,"Business"],
    [32,32,91,"122/70",88,"Neg","32.00%","Neg","Nil","29/52","Ceph","Roa","HD","AA","O+","Neg","Neg",81,"Business"],
    [26,12,99,"125/71",98,"Neg","29.00%","Neg","Nil","35/52","Ceph","Loa","HD","AS","AB+","Neg","Neg",85,"Nurse"],
    [23,16,79,"117/68",90,"Neg","33.00%","Neg","Nil","16/52","Bulky","Loa","HD","AA","O+","Neg","Neg",82,"Secretary"],
    [30,34,69,"107/67",105,"Neg","32.00%","Neg","Nil","34/52","Trans","Loa","HD","AA","O+","Neg","Neg",52,"Business"],
    [37,26,82,"100/60",101,"Neg","32.00%","Neg","Nil","26/52","Bulky","Roa","HD","AA","O-","Neg","Neg",127,"Teacher"],
    [36,31,64,"116/73",80,"Neg","32.00%","Neg","Nil","31/52","Bulky","Loa","HD","AS","R+","Neg","Neg",83,"Business"],
    [27,27,65,"110/70",88,"Neg","33.00%","Trace","Nil","27/52","Ceph","Roa","HD","AA","B+","Neg","Neg",75,"Business"],
    [28,25,79,"134/75",102,"Neg","32.00%","Trace","Nil","25/52","Ceph","Roa","HD","", "","Neg","Neg",90,"Business"],
    [31,17,90,"135/71",105,"Neg","36.00%","Neg","Nil","17/52","Bulky","Loa","HD","AC","-","Neg","Neg",98,"Business"],
    [35,14,54,"95/78",77,"Neg","34.00%","Neg","Nil","14/52","Bulky","Loa","HD","AA","B+","Neg","Neg",136,"Trader"],
    [30,15,89,"118/71",80,"Neg","36.00%","Trace","Nil","15/52","Bulky","Roa","HD","AA","B+","Neg","Neg",104,"Self employed"],
    [34,29,73,"106/69",89,"Neg","36.00%","Neg","Nil","29/52","Ceph","Roa","HD","AA","O+","Neg","Neg",92,"Surveyor"],
    [28,38,68,"120/70",59,"Neg","33.00%","Trace","Nil","38/52","Ceph","Roa","HD","AA","A+","Neg","Neg",118,"Fashion designer"],
    [33,31,69,"102/85",92,"Neg","30.00%","Neg","Nil","31/52","Ceph","Roa","HD","AS","O+","Neg","Neg",105,"Fashion designer"],
    [37,24,69,"120/70",75,"Neg","33.00%","Neg","Nil","24/52","Ceph","Roa","HD","AA","O+","Neg","Neg",95,"Secretary"],
    [39,22,74,"130/76","", "Pos","32.00%","Trace","Nil","22/52","Ceph","Loa","HD","AA","O+","Neg","Neg",76,"Business"],
    [32,36,66,"114/76",108,"Neg","32.00%","Neg","Nil","36/52","Ceph","Roa","HD","AA","O+","Neg","Neg",111,"Business"],
    [26,37,70,"100/84",97,"Neg","34.00%","Neg","Nil","37/52","Ceph","Roa","HD","", "","Neg","Neg",116,"Business"],
]

columns = [
    "Age","Gestational age","Weight","BP","Pulse","Hapetis B","PCV","Urine Sugar",
    "Oedema","Fundal Height","Presentation","Position","FHR","Genotype",
    "Blood Group","XYZ","Malaria","RBS/FBS(mg)","Occupation"
]

df = pd.DataFrame(data, columns=columns)

print(df)


    Age  Gestational age  Weight      BP Pulse Hapetis B     PCV Urine Sugar  \
0    39               36      55   97/74    87       Neg  35.00%         Neg   
1    24               36      60   95/59    73       Neg  32.00%         Neg   
2    32               32      91  122/70    88       Neg  32.00%         Neg   
3    26               12      99  125/71    98       Neg  29.00%         Neg   
4    23               16      79  117/68    90       Neg  33.00%         Neg   
5    30               34      69  107/67   105       Neg  32.00%         Neg   
6    37               26      82  100/60   101       Neg  32.00%         Neg   
7    36               31      64  116/73    80       Neg  32.00%         Neg   
8    27               27      65  110/70    88       Neg  33.00%       Trace   
9    28               25      79  134/75   102       Neg  32.00%       Trace   
10   31               17      90  135/71   105       Neg  36.00%         Neg   
11   35               14      54   95/78

In [90]:
## To import my csv data

import pandas as pd

df = pd.read_csv("pregnancy data.csv")   # replace with your filename
print(df)


     Age  Gestational age  weight      BP Pulse Hapetis B     PCV Urine Sugar  \
0     39               36      55   97/74    87       Neg  35.00%         Neg   
1     24               36      60   95/59    73       Neg  32.00%         Neg   
2     32               32      91  122/70    88       Neg  32.00%         Neg   
3     26               12      99  125/71    98       Neg  29.00%         Neg   
4     23               16      79  117/68    90       Neg  33.00%         Neg   
..   ...              ...     ...     ...   ...       ...     ...         ...   
228   36               38      72  130/90   100       Neg  31.00%         Neg   
229   29               15      50   90/50    73       Neg  30.00%         Neg   
230   38               20      71  120/80    80       Pos  32.00%       Trace   
231   17                8      45   90/50    70       Neg  30.00%         Neg   
232   22               28      52  100/80    71       Neg  33.00%         Neg   

    Oedema Fundal Height  P

In [91]:
df.head

<bound method NDFrame.head of      Age  Gestational age  weight      BP Pulse Hapetis B     PCV Urine Sugar  \
0     39               36      55   97/74    87       Neg  35.00%         Neg   
1     24               36      60   95/59    73       Neg  32.00%         Neg   
2     32               32      91  122/70    88       Neg  32.00%         Neg   
3     26               12      99  125/71    98       Neg  29.00%         Neg   
4     23               16      79  117/68    90       Neg  33.00%         Neg   
..   ...              ...     ...     ...   ...       ...     ...         ...   
228   36               38      72  130/90   100       Neg  31.00%         Neg   
229   29               15      50   90/50    73       Neg  30.00%         Neg   
230   38               20      71  120/80    80       Pos  32.00%       Trace   
231   17                8      45   90/50    70       Neg  30.00%         Neg   
232   22               28      52  100/80    71       Neg  33.00%         Neg  

In [92]:
df.shape ## To chk rows and colomns

(233, 19)

In [93]:
df.index

RangeIndex(start=0, stop=233, step=1)

In [94]:
df["XYZ"]

0      Neg
1      Neg
2      Neg
3      Neg
4      Neg
      ... 
228    Neg
229    Neg
230    Neg
231    Neg
232    Pos
Name: XYZ, Length: 233, dtype: object

In [95]:
df.XYZ

0      Neg
1      Neg
2      Neg
3      Neg
4      Neg
      ... 
228    Neg
229    Neg
230    Neg
231    Neg
232    Pos
Name: XYZ, Length: 233, dtype: object

In [96]:
df[["XYZ", "weight", "Age"]]

XYZ  weight  Age
0    Neg      55   39
1    Neg      60   24
2    Neg      91   32
3    Neg      99   26
4    Neg      79   23
..   ...     ...  ...
228  Neg      72   36
229  Neg      50   29
230  Neg      71   38
231  Neg      45   17
232  Pos      52   22

[233 rows x 3 columns]

In [97]:
import pandas as pd
covid_19 = pd.read_csv("covidset.csv")   # replace with your filename
print(covid_19)

          dateRep  day  month  year  cases  deaths countriesAndTerritories  \
0      01/07/2020    1      7  2020    279      13             Afghanistan   
1      30/06/2020   30      6  2020    271      12             Afghanistan   
2      29/06/2020   29      6  2020    351      18             Afghanistan   
3      28/06/2020   28      6  2020    165      20             Afghanistan   
4      27/06/2020   27      6  2020    276       8             Afghanistan   
...           ...  ...    ...   ...    ...     ...                     ...   
26977  25/03/2020   25      3  2020      0       0                Zimbabwe   
26978  24/03/2020   24      3  2020      0       1                Zimbabwe   
26979  23/03/2020   23      3  2020      0       0                Zimbabwe   
26980  22/03/2020   22      3  2020      1       0                Zimbabwe   
26981  21/03/2020   21      3  2020      1       0                Zimbabwe   

      geoId countryterritoryCode  popData2019 continentExp  
0 

In [98]:
## Feature Engineering
## FAtality Rate

In [99]:
covid_19["Fatality rate"] = covid_19["deaths"]/covid_19["cases"] * 100

In [100]:
covid_19

dateRep  day  month  year  cases  deaths countriesAndTerritories  \
0      01/07/2020    1      7  2020    279      13             Afghanistan   
1      30/06/2020   30      6  2020    271      12             Afghanistan   
2      29/06/2020   29      6  2020    351      18             Afghanistan   
3      28/06/2020   28      6  2020    165      20             Afghanistan   
4      27/06/2020   27      6  2020    276       8             Afghanistan   
...           ...  ...    ...   ...    ...     ...                     ...   
26977  25/03/2020   25      3  2020      0       0                Zimbabwe   
26978  24/03/2020   24      3  2020      0       1                Zimbabwe   
26979  23/03/2020   23      3  2020      0       0                Zimbabwe   
26980  22/03/2020   22      3  2020      1       0                Zimbabwe   
26981  21/03/2020   21      3  2020      1       0                Zimbabwe   

      geoId countryterritoryCode  popData2019 continentExp  Fatality rate  
0        AF                  AFG   38041757.0         Asia       4.659498  
1        AF                  AFG   38041757.0         Asia       4.428044  
2        AF                  AFG   38041757.0         Asia       5.128205  
3        AF                  AFG   38041757.0         Asia      12.121212  
4        AF                  AFG   38041757.0         Asia       2.898551  
...     ...                  ...          ...          ...            ...  
26977    ZW                  ZWE   14645473.0       Africa            NaN  
26978    ZW                  ZWE   14645473.0       Africa            inf  
26979    ZW                  ZWE   14645473.0       Africa            NaN  
26980    ZW                  ZWE   14645473.0       Africa       0.000000  
26981    ZW                  ZWE   14645473.0       Africa       0.000000  

[26982 rows x 12 columns]

In [101]:
## Discharge rate
## discharge_rate = covid_19["cases"] - ["deaths"]

In [102]:
df

Age  Gestational age  weight      BP Pulse Hapetis B     PCV Urine Sugar  \
0     39               36      55   97/74    87       Neg  35.00%         Neg   
1     24               36      60   95/59    73       Neg  32.00%         Neg   
2     32               32      91  122/70    88       Neg  32.00%         Neg   
3     26               12      99  125/71    98       Neg  29.00%         Neg   
4     23               16      79  117/68    90       Neg  33.00%         Neg   
..   ...              ...     ...     ...   ...       ...     ...         ...   
228   36               38      72  130/90   100       Neg  31.00%         Neg   
229   29               15      50   90/50    73       Neg  30.00%         Neg   
230   38               20      71  120/80    80       Pos  32.00%       Trace   
231   17                8      45   90/50    70       Neg  30.00%         Neg   
232   22               28      52  100/80    71       Neg  33.00%         Neg   

    Oedema Fundal Height  Presentation      Position FHR Genotype Blood Group  \
0      Nil         38/52          Ceph           Loa  HD       AA          O+   
1      Nil         36/52          Ceph           Loa  HD      NaN          A+   
2      Nil         29/52          Ceph           Roa  HD       AA          O+   
3      Nil         35/52          Ceph           Loa  HD       AS         AB+   
4      Nil         16/52         Bulky           Loa  HD       AA          O+   
..     ...           ...           ...           ...  ..      ...         ...   
228    Nil         38/52          Ceph           Loa  HD       AA          O-   
229    Nil         18/52         Bulky  Not palpable  HD       AA          A+   
230    Yes         20/52         Trans           Roa  HD       AS          A+   
231    Nil         8/52'  Not palpable           NaN  HD       AA          B+   
232    Nil         28/52          Ceph           Loa  HD       AA         AB+   

     XYZ Malaria   RBS/FBS(mg)   Occupation  
0    Neg      Neg           93    Business   
1    Neg      Neg           71    Business   
2    Neg      Neg           81    Business   
3    Neg      Neg           85        Nurse  
4    Neg      Neg           82    Secetrary  
..   ...      ...          ...          ...  
228  Neg      Nil          150      Teacher  
229  Neg      Yes          100   Pharmacist  
230  Neg      Nil          120  Hairdresser  
231  Neg      Yes           80      Student  
232  Pos      Yes          100      Student  

[233 rows x 19 columns]

In [103]:
df.head

<bound method NDFrame.head of      Age  Gestational age  weight      BP Pulse Hapetis B     PCV Urine Sugar  \
0     39               36      55   97/74    87       Neg  35.00%         Neg   
1     24               36      60   95/59    73       Neg  32.00%         Neg   
2     32               32      91  122/70    88       Neg  32.00%         Neg   
3     26               12      99  125/71    98       Neg  29.00%         Neg   
4     23               16      79  117/68    90       Neg  33.00%         Neg   
..   ...              ...     ...     ...   ...       ...     ...         ...   
228   36               38      72  130/90   100       Neg  31.00%         Neg   
229   29               15      50   90/50    73       Neg  30.00%         Neg   
230   38               20      71  120/80    80       Pos  32.00%       Trace   
231   17                8      45   90/50    70       Neg  30.00%         Neg   
232   22               28      52  100/80    71       Neg  33.00%         Neg  

In [104]:
registration_dict_df

gender  country  ages
0    male    Niger    15
1  female   Uganda    19
2    male  Nigeria    20
3    male  Nigeria    25
4    male  Nigeria    22
5  female  Nigeria    30
6  female  Nigeria    32

In [105]:
registration_dict_df.drop("ages", axis = "columns") 


gender  country
0    male    Niger
1  female   Uganda
2    male  Nigeria
3    male  Nigeria
4    male  Nigeria
5  female  Nigeria
6  female  Nigeria

In [106]:
registration_dict_df

gender  country  ages
0    male    Niger    15
1  female   Uganda    19
2    male  Nigeria    20
3    male  Nigeria    25
4    male  Nigeria    22
5  female  Nigeria    30
6  female  Nigeria    32

In [107]:
## Implace = True dat must be use for Data Transformation to be effective

In [108]:
registration_dict_df_copy = registration_dict_df

In [109]:
registration_dict_df_copy

gender  country  ages
0    male    Niger    15
1  female   Uganda    19
2    male  Nigeria    20
3    male  Nigeria    25
4    male  Nigeria    22
5  female  Nigeria    30
6  female  Nigeria    32

In [110]:
registration_dict_df_copy.drop("ages", axis="columns", inplace=True)  ## Implace: To replace existing dataframe and replace. The column is for the axis


In [111]:
registration_dict_df_copy

gender  country
0    male    Niger
1  female   Uganda
2    male  Nigeria
3    male  Nigeria
4    male  Nigeria
5  female  Nigeria
6  female  Nigeria

In [112]:
covid_19

dateRep  day  month  year  cases  deaths countriesAndTerritories  \
0      01/07/2020    1      7  2020    279      13             Afghanistan   
1      30/06/2020   30      6  2020    271      12             Afghanistan   
2      29/06/2020   29      6  2020    351      18             Afghanistan   
3      28/06/2020   28      6  2020    165      20             Afghanistan   
4      27/06/2020   27      6  2020    276       8             Afghanistan   
...           ...  ...    ...   ...    ...     ...                     ...   
26977  25/03/2020   25      3  2020      0       0                Zimbabwe   
26978  24/03/2020   24      3  2020      0       1                Zimbabwe   
26979  23/03/2020   23      3  2020      0       0                Zimbabwe   
26980  22/03/2020   22      3  2020      1       0                Zimbabwe   
26981  21/03/2020   21      3  2020      1       0                Zimbabwe   

      geoId countryterritoryCode  popData2019 continentExp  Fatality rate  
0        AF                  AFG   38041757.0         Asia       4.659498  
1        AF                  AFG   38041757.0         Asia       4.428044  
2        AF                  AFG   38041757.0         Asia       5.128205  
3        AF                  AFG   38041757.0         Asia      12.121212  
4        AF                  AFG   38041757.0         Asia       2.898551  
...     ...                  ...          ...          ...            ...  
26977    ZW                  ZWE   14645473.0       Africa            NaN  
26978    ZW                  ZWE   14645473.0       Africa            inf  
26979    ZW                  ZWE   14645473.0       Africa            NaN  
26980    ZW                  ZWE   14645473.0       Africa       0.000000  
26981    ZW                  ZWE   14645473.0       Africa       0.000000  

[26982 rows x 12 columns]

In [113]:
covid_19[["day", "month", "year", "cases", "deaths"]] ##selecting list of data from a dataframe

day  month  year  cases  deaths
0        1      7  2020    279      13
1       30      6  2020    271      12
2       29      6  2020    351      18
3       28      6  2020    165      20
4       27      6  2020    276       8
...    ...    ...   ...    ...     ...
26977   25      3  2020      0       0
26978   24      3  2020      0       1
26979   23      3  2020      0       0
26980   22      3  2020      1       0
26981   21      3  2020      1       0

[26982 rows x 5 columns]

In [114]:
covid_19[covid_19["deaths"] == 0]  ## Querying data with a specific condition

dateRep  day  month  year  cases  deaths countriesAndTerritories  \
45     17/05/2020   17      5  2020      0       0             Afghanistan   
62     30/04/2020   30      4  2020    122       0             Afghanistan   
64     28/04/2020   28      4  2020    172       0             Afghanistan   
73     19/04/2020   19      4  2020     63       0             Afghanistan   
79     13/04/2020   13      4  2020     52       0             Afghanistan   
...           ...  ...    ...   ...    ...     ...                     ...   
26976  26/03/2020   26      3  2020      1       0                Zimbabwe   
26977  25/03/2020   25      3  2020      0       0                Zimbabwe   
26979  23/03/2020   23      3  2020      0       0                Zimbabwe   
26980  22/03/2020   22      3  2020      1       0                Zimbabwe   
26981  21/03/2020   21      3  2020      1       0                Zimbabwe   

      geoId countryterritoryCode  popData2019 continentExp  Fatality rate  
45       AF                  AFG   38041757.0         Asia            NaN  
62       AF                  AFG   38041757.0         Asia            0.0  
64       AF                  AFG   38041757.0         Asia            0.0  
73       AF                  AFG   38041757.0         Asia            0.0  
79       AF                  AFG   38041757.0         Asia            0.0  
...     ...                  ...          ...          ...            ...  
26976    ZW                  ZWE   14645473.0       Africa            0.0  
26977    ZW                  ZWE   14645473.0       Africa            NaN  
26979    ZW                  ZWE   14645473.0       Africa            NaN  
26980    ZW                  ZWE   14645473.0       Africa            0.0  
26981    ZW                  ZWE   14645473.0       Africa            0.0  

[18297 rows x 12 columns]

In [115]:
covid_19[covid_19["deaths"] > 2000]  ## Querying data with a specific condition 

dateRep  day  month  year  cases  deaths   countriesAndTerritories  \
8984   04/04/2020    4      4  2020   5233    2004                    France   
11639  17/06/2020   17      6  2020  10974    2003                     India   
25841  26/06/2020   26      6  2020  40949    2437  United_States_of_America   
25890  08/05/2020    8      5  2020  28369    2239  United_States_of_America   
25891  07/05/2020    7      5  2020  24128    2353  United_States_of_America   
25892  06/05/2020    6      5  2020  23841    2144  United_States_of_America   
25896  02/05/2020    2      5  2020  33955    2062  United_States_of_America   
25897  01/05/2020    1      5  2020  29917    2040  United_States_of_America   
25898  30/04/2020   30      4  2020  27326    2611  United_States_of_America   
25899  29/04/2020   29      4  2020  24132    2110  United_States_of_America   
25902  26/04/2020   26      4  2020  48529    2172  United_States_of_America   
25904  24/04/2020   24      4  2020  26543    3179  United_States_of_America   
25906  22/04/2020   22      4  2020  37289    2524  United_States_of_America   
25910  18/04/2020   18      4  2020  30833    3770  United_States_of_America   
25911  17/04/2020   17      4  2020  31667    2299  United_States_of_America   
25912  16/04/2020   16      4  2020  30148    4928  United_States_of_America   
25913  15/04/2020   15      4  2020  26922    2408  United_States_of_America   
25917  11/04/2020   11      4  2020  35527    2087  United_States_of_America   

      geoId countryterritoryCode   popData2019 continentExp  Fatality rate  
8984     FR                  FRA  6.701288e+07       Europe      38.295433  
11639    IN                  IND  1.366418e+09         Asia      18.252233  
25841    US                  USA  3.290649e+08      America       5.951305  
25890    US                  USA  3.290649e+08      America       7.892418  
25891    US                  USA  3.290649e+08      America       9.752155  
25892    US                  USA  3.290649e+08      America       8.992911  
25896    US                  USA  3.290649e+08      America       6.072743  
25897    US                  USA  3.290649e+08      America       6.818866  
25898    US                  USA  3.290649e+08      America       9.555003  
25899    US                  USA  3.290649e+08      America       8.743577  
25902    US                  USA  3.290649e+08      America       4.475674  
25904    US                  USA  3.290649e+08      America      11.976792  
25906    US                  USA  3.290649e+08      America       6.768752  
25910    US                  USA  3.290649e+08      America      12.227159  
25911    US                  USA  3.290649e+08      America       7.259924  
25912    US                  USA  3.290649e+08      America      16.346026  
25913    US                  USA  3.290649e+08      America       8.944358  
25917    US                  USA  3.290649e+08      America       5.874405

In [116]:
## pd.read_type of data
## pd.read_csv()   pd.read_json()
## shape: rows vs column



In [117]:
pwd  ## working dir

'c:\\Users\\PAUL\\Desktop\\Practice'

In [118]:
import pandas as pd

boston_population = pd.read_csv("dataset/boston_population_by_zip.csv")   # replace with your filename
print(boston_population)

     zip_code  Population
0        2301       68571
1        2148       65386
2        2155       62996
3        2360       60793
4        2151       60736
..        ...         ...
529      1380          47
530      2713          34
531      1525          31
532      2553          30
533      2584          30

[534 rows x 2 columns]


In [119]:
boston_population.head

<bound method NDFrame.head of      zip_code  Population
0        2301       68571
1        2148       65386
2        2155       62996
3        2360       60793
4        2151       60736
..        ...         ...
529      1380          47
530      2713          34
531      1525          31
532      2553          30
533      2584          30

[534 rows x 2 columns]>

In [120]:
# To save data in a particular file and send it to a give directory.

boston_population.to_stata("dataset/Boston_population_in_stata")

In [121]:
## Datasets with missing values
##  .isna()
#   .isnull()

In [122]:
covid_19.isnull  ## Missing values

<bound method DataFrame.isnull of           dateRep  day  month  year  cases  deaths countriesAndTerritories  \
0      01/07/2020    1      7  2020    279      13             Afghanistan   
1      30/06/2020   30      6  2020    271      12             Afghanistan   
2      29/06/2020   29      6  2020    351      18             Afghanistan   
3      28/06/2020   28      6  2020    165      20             Afghanistan   
4      27/06/2020   27      6  2020    276       8             Afghanistan   
...           ...  ...    ...   ...    ...     ...                     ...   
26977  25/03/2020   25      3  2020      0       0                Zimbabwe   
26978  24/03/2020   24      3  2020      0       1                Zimbabwe   
26979  23/03/2020   23      3  2020      0       0                Zimbabwe   
26980  22/03/2020   22      3  2020      1       0                Zimbabwe   
26981  21/03/2020   21      3  2020      1       0                Zimbabwe   

      geoId countryterritoryC

In [123]:
covid_19.isnull().sum()  ## Missing Values sum

dateRep                        0
day                            0
month                          0
year                           0
cases                          0
deaths                         0
countriesAndTerritories        0
geoId                        109
countryterritoryCode          64
popData2019                   64
continentExp                   0
Fatality rate              10298
dtype: int64

In [124]:
df.isnull().sum()  ## Missing Values sum

Age                 0
Gestational age     0
weight              0
BP                  0
Pulse               3
Hapetis B           1
PCV                 3
Urine Sugar         0
Oedema              0
Fundal Height       1
Presentation        1
Position           10
FHR                 1
Genotype            8
Blood Group         8
XYZ                 0
Malaria             0
RBS/FBS(mg)         0
Occupation          0
dtype: int64

In [125]:
## DEALING WITH MISSING VALUES


In [126]:
# Using the .dropna() 
# This method is to drop data with missing value 

In [127]:
## Other meathods include mean, mode et.c


In [128]:
## TO IDENTIFY DUPLICATE


In [129]:
## Use the attribute .duplicated

In [130]:
df.duplicated()


0      False
1      False
2      False
3      False
4      False
       ...  
228    False
229    False
230    False
231    False
232    False
Length: 233, dtype: bool

In [ ]:
##  df.duplicated(0)  To use 0 for all missing values

In [131]:
df.duplicated().sum()  ## Total duplicates

np.int64(0)

In [132]:
## 
# Selecting duplicates based on columns
# 

In [133]:
registration_dict_df

gender  country
0    male    Niger
1  female   Uganda
2    male  Nigeria
3    male  Nigeria
4    male  Nigeria
5  female  Nigeria
6  female  Nigeria

In [134]:
registration_dict_df[registration_dict_df.duplicated({"gender", "country"})]  ## 
# Selecting duplicates based on columns


gender  country
3    male  Nigeria
4    male  Nigeria
6  female  Nigeria

In [135]:
registration_dict_df

gender  country
0    male    Niger
1  female   Uganda
2    male  Nigeria
3    male  Nigeria
4    male  Nigeria
5  female  Nigeria
6  female  Nigeria

In [137]:
registration_dict_df.drop_duplicates(inplace=True)

registration_dict_df

gender  country
0    male    Niger
1  female   Uganda
2    male  Nigeria
5  female  Nigeria

In [139]:
### EXPLORATORY DATA ANALYSIS
## Pandas profilling has to be installed in the Terminal